ALTER TABLE users ADD COLUMN IF NOT EXISTS hkdf_salt VARCHAR(128);

ALTER TABLE users ALTER COLUMN auth_hash TYPE VARCHAR(512);
ALTER TABLE users ALTER COLUMN auth_salt TYPE VARCHAR(512);
ALTER TABLE users ALTER COLUMN protected_symmetric_key TYPE VARCHAR(8192);
ALTER TABLE users ALTER COLUMN public_key TYPE VARCHAR(4096);
ALTER TABLE users ALTER COLUMN encrypted_private_key TYPE VARCHAR(16384);
